const cardImages = [
	{
		id: 1,
		name: 'Arizona Diamondbacks',
		img: 'https://www.mlbstatic.com/team-logos/team-cap-on-light/109.svg',
		size: '85%',
		matched: false,
	},
	{
		id: 2,
		name: 'Atlanta Braves',
		img: 'https://www.mlbstatic.com/team-logos/team-cap-on-light/144.svg',
		size: '75%',
		matched: false,
	},
	{
		id: 3,
		name: 'Baltimore Orioles',
		img: 'https://www.mlbstatic.com/team-logos/team-cap-on-light/110.svg',
		size: '75%',
		matched: false,
	},
	{
		id: 4,
		name: 'Boston Red Sox',
		img: 'https://www.mlbstatic.com/team-logos/team-primary-on-light/111.svg',
		size: '75%',
		matched: false,
	},
	{
		id: 5,
		name: 'Chicago Cubs',
		img: 'https://www.mlbstatic.com/team-logos/team-cap-on-light/112.svg',
		size: '80%',
		matched: false,
	},
	{
		id: 6,
		name: 'Chicago White Sox',
		img: 'https://www.mlbstatic.com/team-logos/team-cap-on-light/145.svg',
		size: '55%',
		matched: false,
	},
	{
		id: 7,
		name: 'Cincinnati Reds',
		img: 'https://www.mlbstatic.com/team-logos/team-cap-on-light/113.svg',
		size: '80%',
		matched: false,
	},
	{
		id: 8,
		name: 'Cleveland Guardians',
		img: 'https://www.mlbstatic.com/team-logos/team-cap-on-light/114.svg',
		size: '50%',
		matched: false,
	},
	{
		id: 9,
		name: 'Colorado Rockies',
		img: 'https://www.mlbstatic.com/team-logos/team-cap-on-light/115.svg',
		size: '70%',
		matched: false,
	},
	{
		id: 10,
		name: 'Detroit Tigers',
		img: 'https://www.mlbstatic.com/team-logos/team-cap-on-light/116.svg',
		size: '55%',
		matched: false,
	},
	{
		id: 11,
		name: 'Houston Astros',
		img: 'https://www.mlbstatic.com/team-logos/team-cap-on-light/117.svg',
		size: '75%',
		matched: false,
	},
	{
		id: 12,
		name: 'Kansas City Royals',
		img: 'https://www.mlbstatic.com/team-logos/team-cap-on-light/118.svg',
		size: '70%',
		matched: false,
	},
	{
		id: 13,
		name: 'Los Angeles Angels',
		img: 'https://www.mlbstatic.com/team-logos/team-cap-on-light/108.svg',
		size: '60%',
		matched: false,
	},
	{
		id: 14,
		name: 'Los Angeles Dodgers',
		img: 'https://www.mlbstatic.com/team-logos/team-cap-on-light/119.svg',
		size: '55%',
		matched: false,
	},
	{
		id: 15,
		name: 'Miami Marlins',
		img: 'https://www.mlbstatic.com/team-logos/team-cap-on-light/146.svg',
		size: '75%',
		matched: false,
	},
	{
		id: 16,
		name: 'Milwaukee Brewers',
		img: 'https://www.mlbstatic.com/team-logos/team-cap-on-light/158.svg',
		size: '75%',
		matched: false,
	},
	{
		id: 17,
		name: 'Minnesota Twins',
		img: 'https://www.mlbstatic.com/team-logos/team-cap-on-light/142.svg',
		size: '70%',
		matched: false,
	},
	{
		id: 18,
		name: 'New York Yankees',
		img: 'https://www.mlbstatic.com/team-logos/team-cap-on-light/147.svg',
		size: '70%',
		matched: false,
	},
	{
		id: 19,
		name: 'New York Mets',
		img: 'https://www.mlbstatic.com/team-logos/team-cap-on-light/121.svg',
		size: '60%',
		matched: false,
	},
	{
		id: 20,
		name: 'Oakland Athletics',
		img: 'https://www.mlbstatic.com/team-logos/team-cap-on-light/133.svg',
		size: '75%',
		matched: false,
	},
	{
		id: 21,
		name: 'Philadelphia Phillies',
		img: 'https://www.mlbstatic.com/team-logos/team-cap-on-light/143.svg',
		size: '65%',
		matched: false,
	},
	{
		id: 22,
		name: 'Pittsburgh Pirates',
		img: 'https://www.mlbstatic.com/team-logos/team-cap-on-light/134.svg',
		size: '55%',
		matched: false,
	},
	{
		id: 23,
		name: 'San Diego Padres',
		img: 'https://www.mlbstatic.com/team-logos/team-cap-on-light/135.svg',
		size: '60%',
		matched: false,
	},
	{
		id: 24,
		name: 'San Francisco Giants',
		img: 'https://www.mlbstatic.com/team-logos/team-cap-on-light/137.svg',
		size: '55%',
		matched: false,
	},
	{
		id: 25,
		name: 'Seattle Mariners',
		img: 'https://www.mlbstatic.com/team-logos/team-cap-on-light/136.svg',
		size: '45%',
		matched: false,
	},
	{
		id: 26,
		name: 'St. Louis Cardinals',
		img: 'https://www.mlbstatic.com/team-logos/team-cap-on-light/138.svg',
		size: '60%',
		matched: false,
	},
	{
		id: 27,
		name: 'Tampa Bay Rays',
		img: 'https://www.mlbstatic.com/team-logos/team-cap-on-light/139.svg',
		size: '75%',
		matched: false,
	},
	{
		id: 28,
		name: 'Texas Rangers',
		img: 'https://www.mlbstatic.com/team-logos/team-cap-on-light/140.svg',
		size: '60%',
		matched: false,
	},
	{
		id: 29,
		name: 'Toronto Blue Jays',
		img: 'https://www.mlbstatic.com/team-logos/team-cap-on-light/141.svg',
		size: '85%',
		matched: false,
	},
	{
		id: 30,
		name: 'Washington Nationals',
		img: 'https://www.mlbstatic.com/team-logos/team-cap-on-light/120.svg',
		size: '75%',
		matched: false,
	},
]

export { cardImages }
